Fix grammar
saleor/saleor-docs pull request #1054
Opened 2023-12-13 13:13 UTC by timuric

2023-12-13 13:23 UTC, 2can commented
@timuric please also update the stable version `versioned_docs/version-3.x/overview/why-saleor/extensibility.mdx`

2023-12-13 14:44 UTC, jwgraves2 requested changes

2023-12-13 15:15 UTC, timuric commented on docs/overview/why-saleor/extensibility.mdx
> +- **Improved security.** Tight coupling increases security risks whereas decoupled architecture reduces the attack surface.
I get this correction <img width="538" alt="image" src="https://github.com/saleor/saleor-docs/assets/4006792/6c2b9feb-5c79-41a4-9dc1-d8fab8a5793a">

2023-12-14 09:01 UTC, 2can approved these changes

2023-12-14 09:04 UTC, merged