Add more details about extensibility
saleor/saleor-docs pull request #1057
Opened 2023-12-14 13:14 UTC by timuric

2023-12-25 11:20 UTC, patrys approved these changes

2024-01-03 09:54 UTC, 2can requested changes

2024-01-03 09:54 UTC, 2can commented on docs/developer/extending/overview.mdx
> +Here are some of the examples how API keys can be used:
```suggestion
Here are some examples of how API keys can be used:
```

2024-01-03 09:54 UTC, 2can commented on docs/developer/extending/overview.mdx
> +You might be tempted to just alter small bits of logic and hope to be able to merge updates in the future.
```suggestion
You might be tempted to alter small bits of logic and hope to be able to merge updates in the future.
```

2024-01-03 09:54 UTC, 2can commented on versioned_docs/version-3.x/developer/extending/overview.mdx
> +You might be tempted to just alter small bits of logic and hope to be able to merge updates in the future.
```suggestion
You might be tempted to alter small bits of logic and hope to be able to merge updates in the future.
```

2024-01-03 09:54 UTC, 2can commented on versioned_docs/version-3.x/developer/extending/overview.mdx
> +Here are some of the examples how API keys can be used:
```suggestion
Here are some examples of how API keys can be used:
```

2024-02-01 11:03 UTC, 2can approved these changes

2024-02-01 11:03 UTC, merged