Improve Adyen configuration docs
saleor/saleor-docs pull request #1074
Opened 2024-01-24 15:12 UTC by Cloud11PL

2024-01-29 16:40 UTC, witoszekdev requested changes

2024-01-29 16:40 UTC, witoszekdev commented on docs/developer/app-store/apps/adyen.mdx
> +
One more thing, in webhook settings you need to make sure you have this checked:

![CleanShot 2024-01-29 at 14 08 17@2x](https://github.com/saleor/saleor-docs/assets/4144459/fe36a8bd-f917-479f-9428-40daa546960d)

2024-02-01 09:56 UTC, lkostrowski approved these changes

2024-02-01 09:56 UTC, lkostrowski commented on docs/developer/app-store/apps/adyen.mdx
> +### Configuring Adyen
I think this section is "installing adyen"

and section below will be `### configuring adyen`

2024-02-01 11:00 UTC, 2can commented on versioned_docs/version-3.x/developer/app-store/apps/adyen.mdx
> +The configuration will not work until you save API credentials in Adyen dashboard.
```suggestion
The configuration will not work until you save API credentials in the Adyen dashboard.
```

2024-02-02 14:37 UTC, 2can approved these changes

2024-02-05 07:59 UTC, merged