Gift promotions
saleor/saleor-docs pull request #1080
Opened 2024-02-01 14:24 UTC by IKarbowiak

Documentation for https://github.com/saleor/saleor/pull/15259

Resolves https://github.com/saleor/saleor/issues/15226

⚠️ 
Contains changes from https://github.com/saleor/saleor-docs/pull/1067

2024-02-02 13:11 UTC, zedzior approved these changes
Clear for me

2024-02-05 10:57 UTC, korycins approved these changes

2024-02-06 10:59 UTC, 2can requested changes

2024-02-06 10:59 UTC, 2can commented on docs/developer/discounts/promotions.mdx
> +For gift reward, the promotion rule must specify the available gifts as product variants
```suggestion
For gift rewards, the promotion rule must specify the available gifts as product variants
```

2024-02-06 10:59 UTC, 2can commented on docs/developer/discounts/promotions.mdx
> +For this kind of promotion rule, the `rewardValue` and `rewardValueType` is empty.
```suggestion
For this kind of promotion rule, the `rewardValue` and `rewardValueType` are empty.
```

2024-02-06 10:59 UTC, 2can commented on docs/developer/discounts/promotions.mdx
> +## Completing checkout with gift reward
```suggestion
## Completing checkout with a gift reward
```

2024-02-06 10:59 UTC, 2can commented on docs/developer/discounts/promotions.mdx
> +We can see extra line added to checkout which is marked with `isGift` flag.
```suggestion
We can see an extra line added to checkout which is marked with `isGift` flag.
```

2024-02-06 10:59 UTC, 2can commented on docs/developer/discounts/promotions.mdx
> +    B --> C[For gift promotion rules chose the available product variant from the assigned gifts, with the highest discounted price]
```suggestion
    B --> C[For gift promotion rules choose the available product variant from the assigned gifts, with the highest discounted price]
```

2024-02-09 08:40 UTC, korycins approved these changes

2024-02-09 08:43 UTC, mmiszy approved these changes

2024-02-09 08:43 UTC, merged