Provide docs for order-granted-refund
saleor/saleor-docs pull request #1118
Opened 2024-03-18 15:01 UTC by korycins

Add a chapter related to `OrderGrantedRefund`. 
It also includes the scope of changes described in RFC: https://github.com/saleor/saleor/discussions/15458
The PR with mentioned changes: https://github.com/saleor/saleor/pull/15590

2024-03-20 11:40 UTC, 2can requested changes

2024-03-20 11:40 UTC, 2can commented on docs/developer/payments.mdx
> +Below example shows how to trigger manual refund:
```suggestion
The below example shows how to trigger the manual refund:
```

2024-03-20 11:40 UTC, 2can commented on docs/developer/payments.mdx
> +Manual refund can be triggered by calling `transactionRequestAction`. If the refund is successful, the `transaction.chargedAmount` will be reduced. The order's `authorizeStatus`, `chargeStatus`, and
```suggestion
The manual refund can be triggered by calling `transactionRequestAction`. If the refund is successful, the `transaction.chargedAmount` will be reduced. The order's `authorizeStatus`, `chargeStatus`, and `totalBalance` will also be recalculated based on the new values of `chargedAmount` and `refundedAmount`. This method is useful when handling overcharged orders.
```

2024-03-20 11:40 UTC, 2can commented on docs/developer/payments.mdx
> +The following example shows how to create the granted refund with assigned `TransactionItem` for the order.
```suggestion
The following example shows how to create the granted refund with the assigned `TransactionItem` for the order.
```

2024-03-20 11:40 UTC, 2can commented on docs/developer/payments.mdx
> +Below example shows how to update existing granted refund
```suggestion
The below example shows how to update the existing granted refund
```

2024-03-20 11:40 UTC, 2can commented on docs/developer/payments.mdx
> +The `OrderGrantedRefund.status` field will be updated based on the result of the refund action. The `TransactionEvent`s related to requested action will be accessible via `OrderGrantedRefund.transact
```suggestion
The `OrderGrantedRefund.status` field will be updated based on the result of the refund action. The `TransactionEvent`s related to the requested action will be accessible via `OrderGrantedRefund.transactionEvents` field.
```

2024-03-20 11:40 UTC, 2can commented on docs/developer/payments.mdx
> +  - `removeLines` - List of `OrderGrantedRefundLine`'s IDs which should be removed from `OrderGrantedRefund`.
```suggestion
  - `removeLines` - List of `OrderGrantedRefundLine`'s IDs that should be removed from `OrderGrantedRefund`.
```

2024-03-20 11:40 UTC, 2can commented on docs/developer/payments.mdx
> +    - `reason` - Reason of the planned refund related to the specific line.
```suggestion
    - `reason` - Reason for the planned refund related to the specific line.
```

2024-03-20 11:40 UTC, 2can commented on docs/developer/payments.mdx
> +When processing a refund based on `OrderGrantedRefund`, there are two steps involved. Firstly, an order must be granted a refund, which defines what should be refunded. This step requires the `MANAGE
```suggestion
When processing a refund based on `OrderGrantedRefund`, there are two steps involved. Firstly, an order must be granted a refund, which defines what should be refunded. This step requires the `MANAGE_ORDERS` permission. Secondly, a refund needs to be requested based on the created `OrderGrantedRefund`. This step requires the `HANDLE_PAYMENTS` permission.
```

2024-03-20 11:40 UTC, 2can commented on docs/developer/payments.mdx
> +The current status of the `orderGrantedRefund` is represented by the `status` field. The possible statuses are:
```suggestion
The current status of the `OrderGrantedRefund` is represented by the `status` field. The possible statuses are:
```

2024-03-20 11:40 UTC, 2can commented on docs/developer/payments.mdx
> +  - `addLines`: Lines that should be added to `OrderGrantedrefund`
```suggestion
  - `addLines`: Lines that should be added to `OrderGrantedRefund`
```

2024-03-20 11:42 UTC, 2can commented
@korycins the following paragraph seems a bit complex as a whole. Maybe some visualization with table(s) or split into some smaller paragraphs would make it  a bit simpler to read 

>The `OrderGrantedRefund` has an impact on the `authorizeStatus`, `chargeStatus`, and `totalBalance`, as it reduces the total value used to calculate the `totalBalance`. For example, if an order has a total of 100 USD and a single `TransactionItem` with a `chargedAmount` of 100 USD, the `totalBalance` would be 0, as `chargedAmount` - `order.total` results in 0. Adding a granted refund with an amount of 10 USD would result in a `totalBalance` of 10, as `chargedAmount` - (`order.total` - `grantedRefund.amount`) gives 10. The `chargeStatus` will be `OVERCHARGED`. If a refund request is made based on the defined granted refund and is successfully processed by the payment app, it will reduce the `chargedAmount`. The `totalBalance` will be 0, as `chargedAmount` (90USD) - (`order.total` - `grantedRefund.amount`) gives 0. The `chargeStatus` will be changed to `FULL`.

2024-04-05 14:12 UTC, korycins commented
Thanks @2can  for the review. I applied the requested changes, I also split the mentioned paragraph and added the table.
Let me know what you think!

2024-04-09 12:40 UTC, 2can approved these changes

2024-04-10 13:41 UTC, Droniu approved these changes

2024-04-22 08:51 UTC, merged