Updates Shipping events information about fields that cause circular reference.
saleor/saleor-docs pull request #1121
Opened 2024-03-20 09:19 UTC by 8r2y5

Updates Shipping events information about fields that cause circular reference.

Code PR: https://github.com/saleor/saleor/pull/15636

2024-03-20 09:57 UTC, krzysztofzuraw requested changes

2024-03-20 09:57 UTC, krzysztofzuraw commented on docs/developer/extending/webhooks/synchronous-events/shipping.mdx
> +  :::
Looks like it broke UI 
![CleanShot 2024-03-20 at 10 56 25@2x](https://github.com/saleor/saleor-docs/assets/9116238/39dc8fbf-35c6-45b3-a161-5a38cb43c6c8)
https://saleor-docs-git-updateshippingeventswarning-saleorcommerce.vercel.app/docs/3.x/developer/extending/webhooks/synchronous-events/shipping#filter-shipping-methods

2024-03-21 11:23 UTC, krzysztofzuraw approved these changes

2024-03-21 11:49 UTC, poulch approved these changes

2024-03-22 13:10 UTC, merged