Add docs for a new SMTP app
saleor/saleor-docs pull request #1161
Opened 2024-05-21 13:47 UTC by lkostrowski

2024-05-23 09:52 UTC, 2can requested changes

2024-05-23 09:52 UTC, 2can commented on docs/developer/app-store/apps/smtp/configuration.mdx
> +6. In the events section choose which of the emails should be sent. You can also modify the template of the emails.
```suggestion
6. In the events section, choose which emails should be sent. You can also modify the template of the emails.
```

2024-05-23 09:52 UTC, 2can commented on docs/developer/app-store/apps/smtp/overview.mdx
> +SMTP application is responsible for sending emails and messages to the customers. It is connected to the Saleor API via webhooks, which notify the application about the events. The messages are deliv
```suggestion
SMTP application is responsible for sending emails and messages to customers. It is connected to the Saleor API via webhooks, which notify the application about the events. The messages are delivered by the SMTP protocol configured in the application.
```

2024-05-23 09:52 UTC, 2can commented on docs/developer/app-store/apps/smtp/overview.mdx
> +1. Configure SMTP protocol that will be used to send emails
```suggestion
1. Configure the SMTP protocol that will be used to send emails
```

2024-05-23 09:52 UTC, 2can commented on docs/developer/app-store/apps/smtp/overview.mdx
> +4. Check if SMTP app works correctly by sending test emails
```suggestion
4. Check if the SMTP app works correctly by sending test emails
```

2024-05-23 09:52 UTC, 2can commented on docs/developer/app-store/apps/emails-and-messages/overview.mdx
> +Emails & Messages app is being split into separate SMTP and Sendgrid apps.
```suggestion
Emails and Messages app is being split into separate SMTP and Sendgrid apps.
```

2024-05-23 09:52 UTC, 2can commented on docs/developer/app-store/apps/smtp/overview.mdx
> +## Migration from Emails & Messages app
```suggestion
## Migration from Emails and Messages app
```

2024-05-23 09:52 UTC, 2can commented on docs/developer/app-store/apps/smtp/overview.mdx
> +SMTP app has been extracted from the Emails & Messages app. If you have been using the Emails & Messages app, you can migrate to the SMTP app by following the steps below:
```suggestion
SMTP app has been extracted from the Emails and Messages app. If you have been using the Emails and Messages app, you can migrate to the SMTP app by following the steps below:
```

2024-05-23 09:52 UTC, 2can commented on docs/developer/app-store/apps/smtp/overview.mdx
> +2. Configure the SMTP app with the same settings as the Emails & Messages
```suggestion
2. Configure the SMTP app with the same settings as the Emails and Messages
```

2024-05-23 09:52 UTC, 2can commented on versioned_docs/version-3.x/developer/app-store/apps/emails-and-messages/overview.mdx
> +Emails & Messages app is being split into separate SMTP and Sendgrid apps.
```suggestion
Emails and Messages app is being split into separate SMTP and Sendgrid apps.
```

2024-05-23 09:52 UTC, 2can commented on versioned_docs/version-3.x/developer/app-store/apps/smtp/overview.mdx
> +## Migration from Emails & Messages app
```suggestion
## Migration from Emails and Messages app
```

2024-05-23 09:52 UTC, 2can commented on versioned_docs/version-3.x/developer/app-store/apps/smtp/overview.mdx
> +SMTP app has been extracted from the Emails & Messages app. If you have been using the Emails & Messages app, you can migrate to the SMTP app by following the steps below:
```suggestion
SMTP app has been extracted from the Emails and Messages app. If you have been using the Emails and Messages app, you can migrate to the SMTP app by following the steps below:
```

2024-05-23 09:52 UTC, 2can commented on versioned_docs/version-3.x/developer/app-store/apps/smtp/overview.mdx
> +2. Configure the SMTP app with the same settings as the Emails & Messages
```suggestion
2. Configure the SMTP app with the same settings as the Emails and Messages
```

2024-05-23 09:52 UTC, 2can commented on versioned_docs/version-3.x/developer/app-store/apps/smtp/overview.mdx
> +6. Uninstall the Emails & Messages app
```suggestion
6. Uninstall the Emails and Messages app
```

2024-05-23 09:52 UTC, 2can commented on versioned_docs/version-3.x/developer/app-store/apps/smtp/configuration.mdx
> +6. In the events section choose which of the emails should be sent. You can also modify the template of the emails.
```suggestion
6. In the events section, choose which emails should be sent. You can also modify the template of the emails.
```

2024-05-23 09:52 UTC, 2can commented on versioned_docs/version-3.x/developer/app-store/apps/smtp/configuration.mdx
> +Both services provide a free plan which will allow you to test email delivery.
```suggestion
Both services provide a free plan that will allow you to test email delivery.
```

2024-05-23 09:52 UTC, 2can commented on docs/developer/app-store/apps/smtp/configuration.mdx
> +Both services provide a free plan which will allow you to test email delivery.
```suggestion
Both services provide a free plan that will allow you to test email delivery.
```

2024-05-23 09:52 UTC, 2can commented on versioned_docs/version-3.x/developer/app-store/apps/smtp/overview.mdx
> +SMTP application is responsible for sending emails and messages to the customers. It is connected to the Saleor API via webhooks, which notify the application about the events. The messages are deliv
```suggestion
SMTP application is responsible for sending emails and messages to customers. It is connected to the Saleor API via webhooks, which notify the application about the events. The messages are delivered by the SMTP protocol configured in the application.
```

2024-05-23 09:52 UTC, 2can commented on versioned_docs/version-3.x/developer/app-store/apps/smtp/overview.mdx
> +1. Configure SMTP protocol that will be used to send emails
```suggestion
1. Configure the SMTP protocol that will be used to send emails
```

2024-05-23 09:52 UTC, 2can commented on docs/developer/app-store/apps/smtp/overview.mdx
> +6. Uninstall the Emails & Messages app
```suggestion
6. Uninstall the Emails and Messages app
```

2024-05-23 09:52 UTC, 2can commented on versioned_docs/version-3.x/developer/app-store/apps/smtp/overview.mdx
> +4. Check if SMTP app works correctly by sending test emails
```suggestion
4. Check if the SMTP app works correctly by sending test emails
```

2024-05-29 11:24 UTC, 2can approved these changes

2024-06-03 06:12 UTC, krzysztofzuraw approved these changes

2024-06-03 08:50 UTC, merged