Add additional info on external shipping method response fields
saleor/saleor-docs pull request #1182
Opened 2024-06-14 14:55 UTC by jakubkuc

Add info on extended fields from external shipping method response that are parsed by Saleor. 
It documents changes from [15935](https://github.com/saleor/saleor/pull/15935)

2024-06-14 14:57 UTC, aniav approved these changes

2024-06-25 10:08 UTC, krzysztofwolski approved these changes

2024-06-25 12:42 UTC, 2can requested changes

2024-06-25 12:42 UTC, 2can commented on docs/developer/extending/webhooks/synchronous-events/shipping.mdx
> +Fields: `minimum_delivery_days`, `description`,`metadata` were added to response in **Saleor 3.19**.
```suggestion
Fields: `minimum_delivery_days`, `description`, and `metadata` were added to the response in **Saleor 3.19**.
```

2024-06-25 12:42 UTC, 2can commented on versioned_docs/version-3.x/developer/extending/webhooks/synchronous-events/shipping.mdx
> +Fields: `minimum_delivery_days`, `description`,`metadata` were added to response in **Saleor 3.19**.
```suggestion
Fields: `minimum_delivery_days`, `description`, and `metadata` were added to the response in **Saleor 3.19**.
```

2024-06-25 12:52 UTC, 2can approved these changes

2024-06-25 13:04 UTC, merged