Add tax exemption section to AvaTax app
saleor/saleor-docs pull request #1190
Opened 2024-06-24 09:29 UTC by szczecha

Add information on how to configure tax-exempt products in AvaTax App
https://linear.app/saleor/issue/SHOPX-894/avatax-add-example-doc-how-to-make-tax-exempt

2024-06-25 11:59 UTC, 2can approved these changes

2024-06-25 13:17 UTC, peelar requested changes

2024-06-25 13:17 UTC, peelar commented on docs/developer/app-store/apps/avatax/tax-codes.mdx
> +Go to _Configuration_ → _Taxes_ → _Tax classes_ on the Dashboard. Click _Create class_. Name the tax class "_Tax exempt_" leave the tax rates empty, and click _Save_.
```suggestion
Go to _Configuration_ → _Taxes_ → _Tax classes_ on the Dashboard. Click _Create class_. Name the tax class "_Tax exempt_", leave the tax rates empty, and click _Save_.
```

2024-06-25 13:17 UTC, peelar commented on versioned_docs/version-3.x/developer/app-store/apps/avatax/tax-codes.mdx
> +Go to _Configuration_ → _Taxes_ → _Tax classes_ on the Dashboard. Click _Create class_. Name the tax class "_Tax exempt_" leave the tax rates empty, and click _Save_.
```suggestion
Go to _Configuration_ → _Taxes_ → _Tax classes_ on the Dashboard. Click _Create class_. Name the tax class "_Tax exempt_", leave the tax rates empty, and click _Save_.
```

2024-06-26 07:43 UTC, peelar approved these changes

2024-06-26 08:17 UTC, merged