Add info about externalReferences
saleor/saleor-docs pull request #1191
Opened 2024-06-24 13:45 UTC by korycins

This PR introduces the section for `externalReference`. It also extends the migration-guide about using `externalReference` without proper permissions. 

> [!NOTE]  
> After applying review comments, I will also move the changes to versioned-docs

2024-06-25 12:08 UTC, 2can requested changes

2024-06-25 12:08 UTC, 2can commented on docs/api-usage/external-references.mdx
> +`externalReference` is available in following types:
```suggestion
`externalReference` is available in the following types:
```

2024-06-25 12:08 UTC, 2can commented on docs/api-usage/external-references.mdx
> +Upon creation of a product in the CMS, an id is assigned. This id can then be used to update the `externalReference` of the product in Saleor:
Let's be coherent among all `ID` instances

```suggestion
Upon creation of a product in the CMS, an ID is assigned. This ID can then be used to update the `externalReference` of the product in Saleor:
```

2024-06-26 08:29 UTC, 2can approved these changes
Please don't merge, it should be merged after the change in the versioning

2024-06-26 11:58 UTC, timuric approved these changes

2024-06-26 12:57 UTC, merged