Add quickstart
saleor/saleor-docs pull request #1194
Opened 2024-06-26 18:07 UTC by timuric

About Saleor will be redundant once the Quickstart guide is complete

Todo:
[ ] - Add redirects
[ ] - Massage files into folders similar to unify with navigation
[ ] - Add complete storefront quickstart
[ ] - Rewrite cloud guide without CLI

2024-07-02 16:28 UTC, krzysztofwolski approved these changes

2024-07-03 12:31 UTC, peelar requested changes

2024-07-03 12:31 UTC, peelar commented on docs/quickstart/storefront.mdx
> +            Alternatively, you can [run Saleor locally](/quickstart/running-locally.mdx) using docker.
```suggestion
            Alternatively, you can [run Saleor locally](/quickstart/running-locally.mdx) using Docker.
```

2024-07-03 12:54 UTC, peelar approved these changes

2024-07-03 13:24 UTC, merged