Redesign
saleor/saleor-docs pull request #1204
Opened 2024-07-03 09:20 UTC by timuric

2024-07-03 09:37 UTC, peelar commented
<img width="320" alt="image" src="https://github.com/saleor/saleor-docs/assets/44495184/da2909e7-8807-495d-a2ae-165339d27a29">

**suggestion**: We have "Apps" at the top level of "Customizing", and then inside "Extending" we have "Apps" again. Given that the first one is the link to the App Store section of the docs, I think it should be called "App Store".

Also, once we rename it, I think we could get rid of the "Extending" catalog and unpack its content in the "Customizing" section.

2024-07-03 09:41 UTC, peelar commented
<img width="1045" alt="image" src="https://github.com/saleor/saleor-docs/assets/44495184/ddbb99c6-746c-4ab9-84c8-25fef756941f">

TBH, I am not sure how I feel about removing the top level nav items. I understand the items are now nested in the left sidebar, but for me the experience is a bit inconsistent. There is nothing about the "Core Concepts" or "Apps" sidebar item that suggests there is a lot of content hiding under that label. I think I would leave "Core Concepts", "API Reference" and "App Store" in the top level nav and just remove it from the sidebar.

2024-07-03 09:41 UTC, timuric commented
@peelar the idea is that there is no longer going to be such nested structure, so this section will be split differently

2024-07-03 09:44 UTC, timuric commented
@peelar sorry I forgot to mark this PR as draft as this is WIP

2024-07-03 09:44 UTC, peelar commented on sidebars.js
> +      label: "Quick Start",
**style**: I would go with "Quickstart"

2024-07-03 09:44 UTC, peelar commented on components/Steps/index.jsx
Awesome component 😍

2024-07-03 09:44 UTC, peelar commented
> @peelar sorry I forgot to mark this PR as draft as this is WIP

Ah, got it!

2024-07-04 07:23 UTC, peelar commented on docs/upgrade-guides/GUIDELINES.mdx
**suggestion (non-blocking)**: This is not supposed to be visible in the sidebar (as far as I can see, it is not). I think we can remove this file altogether, this is for internal use only, and we maintain this type of content outside our docs.

2024-07-04 07:24 UTC, peelar requested changes
<img width="319" alt="image" src="https://github.com/saleor/saleor-docs/assets/44495184/62a78526-198b-4a8e-9205-af8f3100dde6">

1. **style (non-blocking)**: "Extending" -> "Webhooks"

<img width="314" alt="image" src="https://github.com/saleor/saleor-docs/assets/44495184/9ffea106-d447-4802-a164-d4623a4fa63c">

2. **style (non-blocking)**: IMO, the "quickstart" in "Cloud quickstart" is redundant here.

3. **suggestion (blocking)**: I think App Store is missing from the sidebar.

4. **thought**: Maybe we could add a new article about App Store to "Why Saleor"? 🤔 Not in this PR, I am just thinking out loud.

2024-07-04 09:29 UTC, krzysztofwolski reviewed
I'm findind myself confused which section I'm in ATM.

![image](https://github.com/saleor/saleor-docs/assets/5188636/bfdc6eaa-be82-43d2-a267-3275c1b100e9)

From the first look its hard to know thats 'building apps' section. Could be mitigated with displaying name of the section in the sidebar or breadcrumbs. 

Besides that im enjoying a new look :+1:

2024-07-04 13:23 UTC, timuric commented
@peelar on one hand Extending section is mostly about webhooks but there is also an overview that generally explains extensibility, imo we should evolve that section beyond webhooks, for example describing middleware pattern, automation etc

2024-07-04 13:49 UTC, timuric commented
@krzysztofwolski I am planning to add titles with icons to each sidebar section, but this PR is becoming too broad, so I will address it in a smaller follow up refinement

2024-07-04 14:15 UTC, timuric commented on docs/upgrade-guides/GUIDELINES.mdx
done

2024-07-04 14:31 UTC, timuric commented
@peelar agree about removing kickstart but unfortunately there are barely any docs in Cloud section, so I used it as a link there, which would be confusing without a full label, this is a temporary measure until we write more docs for cloud 
<img width="320" alt="image" src="https://github.com/saleor/saleor-docs/assets/4006792/16c269f4-8ff5-43ab-8d4b-ebc5fd4d1c22">

2024-07-05 06:25 UTC, peelar approved these changes

2024-07-05 07:29 UTC, merged