Extend pricing page with the amount precision
saleor/saleor-docs pull request #1214
Opened 2024-07-08 10:05 UTC by IKarbowiak

Make it clear what is the precision of returned prices.

2024-07-08 10:12 UTC, lkostrowski approved these changes

2024-07-08 12:36 UTC, timuric commented on docs/api-usage/prices.mdx
> +The numeric amount precision is determined by the precision of the price currency.
I would suggest adding an example:

 The numeric amount precision is determined by the precision of the price currency. For example, USD has a precision value of 2, such as $1.00

2024-07-11 06:35 UTC, peelar requested changes

2024-07-11 06:35 UTC, peelar commented on docs/api-usage/prices.mdx
> +The numeric amount precision is determined by the precision of the price currency. For example, USD has a precision value of 2, such as $1.00
```suggestion
The numeric amount precision is determined by the precision of the price currency. For example, USD has a precision value of 2, such as $1.00.
```

2024-07-11 08:07 UTC, timuric approved these changes

2024-07-11 08:09 UTC, peelar approved these changes

2024-07-11 08:12 UTC, merged

2024-07-11 13:09 UTC, IKarbowiak commented
Thank you guys for taking care of that! ❤️  🚀