Add info about amount precision in transaction API
saleor/saleor-docs pull request #1254
Opened 2024-07-25 10:56 UTC by IKarbowiak

Docs for https://github.com/saleor/saleor/pull/16410

2024-07-25 11:25 UTC, timuric submitted a review, later dismissed

2024-07-29 10:49 UTC, krzysztofwolski requested changes

2024-07-29 11:53 UTC, timuric commented on docs/developer/payments/transactions.mdx
> +The amounts provided in the transaction input data are rounded based on the given currency precision.
@krzysztofwolski please add this example and let's merge it 🎉

2024-07-30 06:28 UTC, IKarbowiak commented on docs/developer/payments/transactions.mdx
> +The amounts provided in the transaction input data are rounded based on the given currency precision.
Updated. Please check

2024-07-30 10:15 UTC, krzysztofwolski approved these changes

2024-07-30 14:16 UTC, merged