Checkout refactoring
saleor/saleor-docs pull request #1264
Opened 2024-07-30 12:23 UTC by timuric

2024-08-06 12:50 UTC, krzysztofwolski requested changes
Small change requested (we have better page for product related issues which should be linked). Besides that 👍

2024-08-06 12:50 UTC, krzysztofwolski commented on docs/developer/checkout/troubleshooting.mdx
> +Make sure product is available in the channel the checkout is created.
Product related issues should be redirected to this page: https://docs.saleor.io/developer/products/troubleshooting

2024-08-06 14:22 UTC, korycins approved these changes

2024-08-07 07:25 UTC, peelar submitted a review, later dismissed

2024-08-07 07:25 UTC, peelar commented on docs/developer/checkout/troubleshooting.mdx
> +2. Shipping methods can be available only for specific countries, if checkout does not contain shipping country the default country of the channel will be used.
```suggestion
2. Shipping methods can be available only for specific countries. If checkout does not contain shipping country, the default country of the channel will be used.
```

2024-08-07 10:53 UTC, krzysztofwolski approved these changes

2024-08-07 11:54 UTC, merged