Remove email & messages app from docs
saleor/saleor-docs pull request #1303
Opened 2024-08-21 12:16 UTC by poulch

2024-08-21 13:16 UTC, lkostrowski approved these changes

2024-08-21 13:16 UTC, lkostrowski commented on docs/developer/app-store/legacy-plugins/user-emails.mdx
> +If you plan on building a new integration with Saleor, we recommend using the [SMTP](../apps/smtp/overview) app instead.
you can also link to sendgrid app example repo

2024-08-23 05:39 UTC, korycins commented
In app's overview, there is:
```
If you plan to use SMTP server, please use the [SMTP app](https://docs.saleor.io/developer/app-store/apps/smtp/overview) 
instead. Emails and Messages app is being split into separate SMTP and Sendgrid apps.
```
But what about sendgrid? Do we have a replacement for that? I don't see any section about Sendgrid. If I am using sengrid provider, what app should I use? 

Also, wouldn't be better to leave the section for `Email and Messages` with big warning label (including side-bar) that the app is depreceated/abandoned/not available on the market anymore, and you should move to App Smtp for Smtp provider and to App X for Sendgrid provider?

2024-08-23 10:01 UTC, krzysztofwolski requested changes
Maciek summed it up perfectly.
The app has users, it was mentioned in a few places so there will be people expecting to find information about it in the docs.
Removing info about it from docs adds to the confusion, not resolve it. Wait till migration is over and then remove it from docs.

2024-08-24 21:18 UTC, closed without merging