Update docs
saleor/saleor-docs pull request #319
Opened 2021-09-25 07:58 UTC by piotrgrundas

2021-09-25 07:58 UTC, patrys commented
Task linked: [SALEOR-4568 Extend accountRegister mutation](https://app.clickup.com/t/2549495/SALEOR-4568)

2021-09-27 08:10 UTC, tomaszszymanski129 requested changes

2021-09-27 08:10 UTC, tomaszszymanski129 commented on docs/developer/api-reference/inputs/account-register-input.mdx
> +
Something went wrong here, password summary is in line 37 and header in 27

2022-03-08 10:16 UTC, krzysztofwolski commented
API reference has been updated

2022-03-08 10:16 UTC, closed without merging