Add documentation for Apollo Federation support
saleor/saleor-docs pull request #325
Opened 2021-10-04 18:10 UTC by rafalp

Adds documentation for changes introduced in https://github.com/mirumee/saleor/pull/8273 but also adds bunch of extra knowledge that should be useful to folk seeking to federate their GraphQL services with Saleor.

2021-10-18 10:11 UTC, maarcingebala commented on docs/developer/apollo-federation.mdx
> +Rely on webhooks to update or clear relations stored in your service's database when objects are deleted in the Saleor.
```suggestion
Rely on webhooks to update or clear relations stored in your service's database when objects are deleted in Saleor.
```

2021-10-18 10:18 UTC, maarcingebala commented on docs/developer/running-saleor/configuration.mdx
> +Sets upper limit on how many entities may be requested by Apollo Federation's gateway for single GraphQL Query. Defaults to `100`. Set to `0` to remove this limit.
```suggestion
Sets upper limit on how many entities may be requested by Apollo Federation's gateway for a single GraphQL query. Defaults to `100`. Set to `0` to remove this limit.
```

2021-10-21 12:21 UTC, krzysztofwolski requested changes

2021-11-03 15:46 UTC, rafalp commented
Moved federation docs under dev/extending as suggested by @krzysztofwolski

2021-11-04 11:02 UTC, maarcingebala approved these changes

2021-11-15 11:08 UTC, maarcingebala commented
@krzysztofwolski Can you re-review this one?

2021-11-15 13:13 UTC, krzysztofwolski approved these changes

2021-11-15 13:13 UTC, krzysztofwolski commented
LGTM!

2021-11-15 13:35 UTC, merged