Add documentation for NP Atobarai
saleor/saleor-docs pull request #342
Opened 2021-11-30 12:03 UTC by stnatic

2021-11-30 14:27 UTC, mateuszgrzyb commented
There should be an NP Atobarai entry on
`/developer/extending/plugins#built-in-plugins`

2021-11-30 14:27 UTC, mateuszgrzyb approved these changes

2021-12-07 00:15 UTC, krzysztofwolski requested changes

2021-12-07 00:15 UTC, krzysztofwolski commented on docs/developer/available-plugins/np-atobarai.mdx
> +For an up to date list of NP error codes please refer to the NP documentation.
Would be useful to link the docs

2021-12-07 00:15 UTC, krzysztofwolski commented on docs/developer/available-plugins/np-atobarai.mdx
> +{"checkoutComplete": {"order": null, "errors": [{"field": null, "message": "TR#E0100065"}]}}
Please format the responses

2021-12-07 00:15 UTC, krzysztofwolski commented on docs/developer/available-plugins/np-atobarai.mdx
> +address as well as a Japanese phone number (country code: `+81`) and only supports payments in Japanese yen (`JPY`).
```suggestion
Please note that NP Atobarai is only applicating to the Japanese market, as it requires:
- a Japanese postal address
- a Japanese phone number (country code: `+81`) 
- only supports payments in Japanese yen (`JPY`)
- the shipment has to be fulfilled using one of the supported local carriers
```

2021-12-07 15:10 UTC, stnatic commented on docs/developer/available-plugins/np-atobarai.mdx
> +In case of errors, NP recommends to display an error according to the communication guidelines available in their documentation.
It's password protected

2021-12-07 15:10 UTC, stnatic commented on docs/developer/available-plugins/np-atobarai.mdx
> +For an up to date list of NP error codes please refer to the NP documentation.
It's password protected

2022-02-20 21:40 UTC, stnatic commented
SALEOR-4968

2022-02-21 17:40 UTC, patrys approved these changes

2022-02-22 10:23 UTC, krzysztofwolski approved these changes

2022-02-22 10:23 UTC, merged