Add basic explanaition of app's extensions
saleor/saleor-docs pull request #348
Opened 2022-01-17 11:18 UTC by korycins

It adds more context to how App's extensions can be used.

2022-01-17 13:06 UTC, krzysztofwolski requested changes
Content looks ok

2022-01-17 13:06 UTC, krzysztofwolski commented on docs/developer/extending/apps/extensions.mdx
> +- `openAs` - Way of opening an extension's url. Default to `POPUP`.
Please add dots at the end of all items or remove.

2022-01-17 13:06 UTC, krzysztofwolski commented on docs/developer/extending/apps/manifest.mdx
> +- `extensions`: List of extensions that will be mounted in Saleor's dashboard. See [extension section](developer/extending/apps/extensions.mdx#key-concepts).
```suggestion
- `extensions`: List of extensions that will be mounted in Saleor's dashboard. See [extension section](developer/extending/apps/extensions.mdx#key-concepts)
```

2022-01-19 09:35 UTC, jwm0 commented on docs/developer/extending/apps/extensions.mdx
> +App extension allows extending different dashboard views by mounting extension iframe or by redirecting user on main App's iframe.
```suggestion
App extensions allow extending different dashboard views by mounting the extension app inside a popup or redirecting users to the main app's page. The app is created as a secure iframe that protects against XSS attacks. 
```

2022-01-19 09:35 UTC, jwm0 commented on docs/developer/extending/apps/extensions.mdx
> +This is a way for customizing and extending dashboard solutions.
```suggestion
It provides a way for customizing and extending the dashboard while keeping the code separate.
```

2022-01-19 09:35 UTC, jwm0 commented on docs/developer/extending/apps/extensions.mdx
> +Below sample manifest, defines two extensions that will be attached to dashboard.
```suggestion
Apps can have multiple extensions. The extension is added by specifying it in the app's manifest. 
The below sample manifest defines two extensions that will be attached to the dashboard:
```

2022-01-19 09:35 UTC, jwm0 commented on docs/developer/extending/apps/extensions.mdx
> +- `label` - Name which will be displayed in dashboard
```suggestion
- `label` - Name which will be displayed in the dashboard
```

2022-01-19 09:35 UTC, jwm0 commented on docs/developer/extending/apps/extensions.mdx
> +- `target` - Direct target on given view&type where extension will be attached
```suggestion
- `target` - Direct target on given view & type where extension will be attached
```

2022-01-19 09:35 UTC, jwm0 commented on docs/developer/extending/apps/extensions.mdx
> +`POPUP` will mount extension in iframe view. `APP_PAGE` will redirect user to app page on dashboard side.
```suggestion
`POPUP` will mount extension in an iframe view. `APP_PAGE` will redirect users to the dashboard's app page.
```

2022-02-01 14:03 UTC, korycins commented on docs/developer/extending/apps/manifest.mdx
> +        "mount": "PRODUCT_OVERVIEW_CREATE",
I've talked with @jwm0 and we agree that for now, we will leave `mount` as a str. In the future we will be able to extend `mount` to support `list` and `str`

2022-02-02 12:14 UTC, karolkielecki requested changes

2022-02-02 12:14 UTC, karolkielecki commented on docs/developer/extending/apps/extensions.mdx
> +Saleor requires that extension will define place of mounting. The below table explains all mounting places available in Saleor.
```suggestion
Saleor requires that extension will define a place of mounting. The below table explains all mounting places available in Saleor.
```

2022-02-02 12:14 UTC, karolkielecki commented on docs/developer/extending/apps/manifest.mdx
> +- `extensions`: List of extensions that will be mounted in Saleor's dashboard. See [extension section](developer/extending/apps/extensions.mdx#key-concepts)
```suggestion
- `extensions`: List of extensions that will be mounted in Saleor's dashboard. For details, please see the [extension section](developer/extending/apps/extensions.mdx#key-concepts)
```

2022-02-03 09:41 UTC, karolkielecki approved these changes

2022-02-03 10:25 UTC, krzysztofwolski approved these changes

2022-02-03 10:54 UTC, merged