Documentation for the read replicas
saleor/saleor-docs pull request #372
Opened 2022-03-01 13:59 UTC by fowczarek

Documentation for the read replicas

2022-03-01 14:00 UTC, patrys commented
Task linked: [SALEOR-4526 Implement database read replicas](https://app.clickup.com/t/2549495/SALEOR-4526)

2022-03-01 15:08 UTC, krzysztofwolski commented on docs/developer/running-saleor/read-replicas.mdx
> +> Product.objects.using(self.database_connection_name).in_bulk(keys)
```suggestion
`database_connection_name` as a part of the base `Dataloader` class. All dataloaders ORM queries should use this variable as connection name, for example:
```python
    Product.objects.using(self.database_connection_name).in_bulk(keys)
```

2022-03-01 15:17 UTC, maarcingebala commented on docs/developer/running-saleor/read-replicas.mdx
> +To specify which connection should be used by ORM we use [`using` on queryset.](https://docs.djangoproject.com/en/4.0/topics/db/multi-db/#manually-selecting-a-database)
```suggestion
To specify which connection to use in ORM, use the [`using` queryset method.](https://docs.djangoproject.com/en/4.0/topics/db/multi-db/#manually-selecting-a-database)
```

2022-03-01 15:17 UTC, maarcingebala commented on docs/developer/running-saleor/read-replicas.mdx
> +> To fetch all products from the primary database we could use:
```suggestion
> To fetch all products from the primary database use:
```

2022-03-01 15:17 UTC, maarcingebala commented on docs/developer/running-saleor/read-replicas.mdx
> +> To fetch all products from the read replica we could use:
```suggestion
> To fetch all products from the read replica use:
```

2022-03-01 15:17 UTC, maarcingebala commented on docs/developer/running-saleor/read-replicas.mdx
> +Do not forget about importing the proper connection name from settings.
We could also add this import in the snippets above so it is clear where do these values come from.

2022-03-01 15:17 UTC, maarcingebala commented on docs/developer/running-saleor/read-replicas.mdx
> +To simulate read replica on the local machine we could use the second connection to the primary database with the read-only user.
```suggestion
To simulate a read replica on the local machine, use the second connection to the primary database with the read-only user.
```

2022-03-01 15:17 UTC, maarcingebala commented on docs/developer/running-saleor/read-replicas.mdx
> +To setup it we should add read-only user to database
1. Add a read-only user in your database:
```
SQL example to create the user
```
If you're using the [saleor-platform](link), you will have a read-only user created automatically.

2. Add the following configuration in `settings.py`:

```
full example from settings.py
```

2022-03-03 09:35 UTC, krzysztofwolski requested changes
Only lil thing and LGTM

2022-03-03 09:35 UTC, krzysztofwolski commented on docs/developer/running-saleor/read-replicas.mdx
> +By default Saleor always uses the primary database. To specify which connection to use in ORM, use [the `using` queryset method.](https://docs.djangoproject.com/en/4.0/topics/db/multi-db/#manually-se
```suggestion
By default Saleor always uses the primary database. To specify which connection to use in ORM, use [the `using` queryset method](https://docs.djangoproject.com/en/4.0/topics/db/multi-db/#manually-selecting-a-database).
```

2022-03-03 10:00 UTC, maarcingebala approved these changes
😍

2022-03-03 20:22 UTC, tomaszszymanski129 approved these changes

2022-03-07 10:55 UTC, karolkielecki requested changes

2022-03-07 10:55 UTC, karolkielecki commented on docs/developer/running-saleor/read-replicas.mdx
> +Database read replica is a read-only copy of the primary database. Replica should reflect changes in the primary database as fast as possible. This feature allows Saleor to offload the primary databa
```suggestion
Database read replica is a read-only copy of the primary database. Replica should reflect changes in the primary database as fast as possible. This feature allows Saleor to offload the primary database by moving the read-only traffic to a separate database.
```

2022-03-07 10:55 UTC, karolkielecki commented on docs/developer/running-saleor/read-replicas.mdx
> +traffic to a separate database.
```suggestion

```

2022-03-07 10:55 UTC, karolkielecki commented on docs/developer/running-saleor/read-replicas.mdx
> +To simulate a read replica on the local machine, use the second connection to the primary database with the read-only user.
```suggestion
To simulate a read replica on a local machine, use a second connection to the primary database with the read-only user.
```

2022-03-07 10:55 UTC, karolkielecki commented on docs/developer/running-saleor/read-replicas.mdx
> +To start using read replica in Saleor set `DATABASE_CONNECTION_REPLICA_NAME` in `settings.py` and specify this connection in `DATABASES`.
```suggestion
To start using read replica in Saleor, set `DATABASE_CONNECTION_REPLICA_NAME` in `settings.py` and specify this connection in `DATABASES`.
```

2022-03-07 10:55 UTC, karolkielecki commented on docs/developer/running-saleor/read-replicas.mdx
> +By default Saleor always uses the primary database. To specify which connection to use in ORM, use [the `using` queryset method](https://docs.djangoproject.com/en/4.0/topics/db/multi-db/#manually-sel
```suggestion
Saleor always uses the primary database by default. To specify which connection to use in ORM, use [the `using` queryset method](https://docs.djangoproject.com/en/4.0/topics/db/multi-db/#manually-selecting-a-database).
```

2022-03-07 10:55 UTC, karolkielecki commented on docs/developer/running-saleor/read-replicas.mdx
> +Saleor-platform creates read-only user by default.
```suggestion
Saleor-platform creates a read-only user by default.
```

2022-03-07 12:36 UTC, karolkielecki approved these changes

2022-03-07 12:37 UTC, merged