Update email palyoads
saleor/saleor-docs pull request #387
Opened 2022-03-22 14:18 UTC by L3str4nge

Related to [Saleor #9388](https://github.com/saleor/saleor/pull/9388)

2022-03-22 14:18 UTC, patrys commented
Task linked: [SALEOR-4283 Convert IDs from DB to Graphql format in Email Payload](https://app.clickup.com/t/2549495/SALEOR-4283)

2022-03-22 17:22 UTC, krzysztofwolski requested changes

2022-03-22 17:22 UTC, krzysztofwolski commented on docs/developer/available-plugins/user-emails.mdx
> +      "id": VXNlcjo1Mg==,
```suggestion
      "id": "VXNlcjo1Mg==",
```

2022-03-23 06:44 UTC, tomaszszymanski129 commented on docs/developer/available-plugins/user-emails.mdx
> +    "id": "VXNlcjo1MQ==",
that has `User` type encoded while it's an `Order` (relates to entire pr). If as a dev I read these docs and wonder what actually hides behind this magic ID, I'd immediately spot this looks like b64, decode it and get confused ;D

2022-03-28 09:18 UTC, maarcingebala commented
@L3str4nge Since this is a breaking change we should mention it in the migration guide. Similarly as we have [3.0->3.1](https://docs.saleor.io/docs/3.x/developer/upgrade-guide/3-0-to-3-1), we should add 3.1 -> 3.2 page and mention this change with some example how the old payload looked like and how it's changed now.

2022-03-30 08:05 UTC, tomaszszymanski129 approved these changes

2022-03-31 07:10 UTC, krzysztofwolski requested changes

2022-03-31 07:10 UTC, krzysztofwolski commented on docs/developer/upgrade-guide/3-1-to-3-2.mdx
> +```
```suggestion
```json
```

2022-03-31 07:10 UTC, krzysztofwolski commented on docs/developer/upgrade-guide/3-1-to-3-2.mdx
> +```
```suggestion
```json
```

2022-03-31 07:10 UTC, krzysztofwolski commented on docs/developer/upgrade-guide/3-1-to-3-2.mdx
> +This change converts ID's from Database to GraphQL format in all notification payloads (email plugins and webhook.NOTIFY).
```suggestion
This change converts ID's from integers to GraphQL format in all notification payloads (email plugins and `NOTIFY` webhook).
```

2022-03-31 07:50 UTC, maarcingebala approved these changes

2022-04-04 11:51 UTC, merged