Add new collection screenshots
saleor/saleor-docs pull request #392
Opened 2022-03-23 12:35 UTC by karolkielecki

2022-03-23 14:38 UTC, Qasem-h approved these changes

2022-04-08 09:33 UTC, krzysztofwolski requested changes
Waiting for the fix on the frontend side to remove unnecessary scrollbars

2022-08-09 12:38 UTC, peelar commented
Hi @karolkielecki 👋 

What is the status here? Do we still need it?

2022-08-11 12:24 UTC, karolkielecki commented
@peelar IMHO, if we change our docs structure and approach (less or no screenshots) -- then I think it's not needed.

2022-08-11 12:25 UTC, closed without merging