Webhook event types enums update
saleor/saleor-docs pull request #400
Opened 2022-04-06 10:09 UTC by SzymJ

New events added to webhooks event enums.

2022-04-06 10:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/saleor/saleor-docs?pullRequest=400) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/saleor/saleor-docs?pullRequest=400) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/saleor/saleor-docs?pullRequest=400) it.</sub>

2022-04-07 08:47 UTC, krzysztofwolski approved these changes

2022-04-07 08:49 UTC, krzysztofwolski requested changes
Please update list of available webhooks too: https://docs.saleor.io/docs/3.x/developer/extending/apps/asynchronous-webhooks#available-webhook-events

2022-04-07 15:31 UTC, CossackDex approved these changes

2022-04-08 12:23 UTC, merged