Add basic info about handling transaction-action-request webhook
saleor/saleor-docs pull request #432
Opened 2022-05-31 06:16 UTC by korycins

Add some basic info about a new webhook that is triggered when a staff user or app is requesting some action on a transaction.

2022-05-31 13:18 UTC, patrys commented
I think it's time we split https://saleor-docs-6i7u5r4oj-saleorcommerce.vercel.app/docs/3.x/developer/checkout, turn it into a category in the sidebar, leave only the intro in this document, and move every section into its own document under `docs/developer/checkout/*.mdx`.

2022-06-21 11:44 UTC, timuric approved these changes

2022-06-24 12:38 UTC, karolkielecki requested changes

2022-06-24 12:38 UTC, karolkielecki commented on docs/developer/checkout.mdx
> +### Handling an action request for transaction
```suggestion
### Handling an action request for a transaction
```

2022-06-24 12:38 UTC, karolkielecki commented on docs/developer/checkout.mdx
> +Action request is called when a staff user or an app triggers a request of action that should be called for a given transaction.
```suggestion
An action request is called when a staff user or an app triggers a request of an action that should be called for a given transaction.
```

2022-06-24 12:38 UTC, karolkielecki commented on docs/developer/checkout.mdx
> +If your app should also process payment request actions (like charge, refund, or void) triggered by staff users on
```suggestion
If your app should also process payment request actions (like charge, refund, or void) triggered by staff users on the 
```

2022-06-24 12:38 UTC, karolkielecki commented on docs/developer/checkout.mdx
> +Saleor dashboard side or by app, make sure that your app is subscribed to
```suggestion
Saleor dashboard side or by the app, make sure that your app is subscribed to the
```

2022-06-24 12:38 UTC, karolkielecki commented on docs/developer/checkout.mdx
> +The below chart shows a workflow for handling `refund` request.
```suggestion
The chart below shows a workflow for handling a `refund` request.
```

2022-06-24 12:38 UTC, karolkielecki commented on docs/developer/checkout.mdx
>  In order not to overflow the database, unfinished checkouts are deleted.
```suggestion
In order not to overload the database, unfinished checkouts are deleted.
```

2022-06-24 12:38 UTC, karolkielecki commented on docs/developer/extending/apps/sample-webhook-payloads.mdx
> +`TRANSACTION_ACTION_REQUEST` is called after requesting a change in transaction state (called by staff user or by an app).
```suggestion
`TRANSACTION_ACTION_REQUEST` is called after requesting a change in transaction state (called by a staff user or by an app). 
```

2022-06-24 12:38 UTC, karolkielecki commented on docs/developer/extending/apps/sample-webhook-payloads.mdx
> +The `transaction` contains all details related to `TransactionItem` object for which the requested action should be called.
```suggestion
The `transaction` contains all details related to the `TransactionItem` object for which the requested action should be called.
```

2022-06-24 12:38 UTC, karolkielecki commented on docs/developer/checkout.mdx
> +The below charts show the workflow of a checkout process.
```suggestion
The charts below show the workflow of a checkout process.
```

2022-07-04 07:09 UTC, timuric commented
@korycins grammar improvements were added, please resolve conflict so we can merge

2022-07-04 10:43 UTC, korycins commented
@timuric Done

2022-08-03 10:56 UTC, peelar commented
@korycins What's the situation here? Do we still need it? If so, please resolve the conflicts and I will handle the rest.

2022-08-04 08:48 UTC, korycins commented
@peelar no more conflicts 🤗

2022-08-04 09:28 UTC, peelar approved these changes

2022-08-04 09:28 UTC, merged