Add upgrade guide 3.11 to 3.12
saleor/saleor-docs pull request #647
Opened 2023-02-03 10:02 UTC by kadewu

Migration upgrade guide. To be merged after succesfull resolving all PR's from issue: https://github.com/saleor/saleor/issues/11337

2023-02-09 10:30 UTC, peelar requested changes

2023-02-09 10:30 UTC, peelar commented on docs/upgrade-guides/3-11-to-3-12.mdx
> +Version 3.12 introduces new fields in our model. To properly migrate from to 3.12 please migrate first to version 3.11.4
```suggestion
Version 3.12 introduces new fields in our model. To successfully upgrade from version 3.11.x to 3.12, please migrate to 3.11.4 first.
```

2023-02-09 10:30 UTC, peelar commented on docs/upgrade-guides/3-11-to-3-12.mdx
> +In version 3.12 `orderSettings` were moved to `Channel`. For more info relate to https://github.com/saleor/saleor/blob/main/CHANGELOG.md
```suggestion
For more info relate to https://github.com/saleor/saleor/blob/main/CHANGELOG.md
```

Three points here:
- please make sure to include the "." at the end of the sentence
- please format the links, e.g. `[Changelog](https://github.com/saleor/saleor/blob/main/CHANGELOG.md)`
- the sentence should probably be something like "for more related information, please...", but...

...I think the documentation should be the source of truth here. Changelog is a nice addition, but we should at least briefly inform about the consequences of the appointed changes.

2023-02-09 10:42 UTC, peelar commented
You can have a look at [the writing documentation guidelines](https://github.com/saleor/saleor-docs/blob/main/GUIDELINES.md) I just merged.

2023-02-15 08:48 UTC, korycins commented on docs/upgrade-guides/3-11-to-3-12.mdx
> +Version 3.12 introduces new fields in our model. To properly migrate from to 3.12 please migrate first to version 3.11.4
I think that we could be more specific than `our model`. Also, for someone who is not familiar with Django, the meaning of `model` can be not fully understood. 
Also, I think, that the preparation section should be more generic. I am going to add a migration guide related to the transaction and changes in the preview feature part, and the current preparation content looks like something strictly related to the channel changes.
Would be also good to mention, that the mentioned request to bump to 3.11.4 first, is strictly related to the zero downtime upgrade. This step can be skipped by someone who doesn't care about it. Or he doesn't use Saleor in production yet.

2023-02-24 10:07 UTC, peelar commented
@IKarbowiak I merged your changes here.

2023-02-24 10:07 UTC, peelar commented
@IKarbowiak Please provide a link to an example API Reference object field that will be affected by these changes.

2023-02-28 07:59 UTC, IKarbowiak commented
@peelar done :)

2023-02-28 09:53 UTC, peelar approved these changes

2023-02-28 10:12 UTC, peelar commented
@korycins will you be reviewing?

2023-02-28 15:13 UTC, korycins approved these changes

2023-02-28 18:20 UTC, merged