Add docs to the CRM App
saleor/saleor-docs pull request #706
Opened 2023-04-03 13:18 UTC by lkostrowski

2023-04-04 07:30 UTC, peelar requested changes

2023-04-04 07:30 UTC, peelar commented on docs/developer/app-store/apps/crm.mdx
> +- Have `MANAGE_APPS` permission
```suggestion
- Have a Saleor user with `MANAGE_APPS` permission
```

2023-04-04 07:30 UTC, peelar commented on docs/developer/app-store/apps/crm.mdx
> +The App can be installed from Saleor App Store. To install the App, you must have `MANAGE_USERS` and `MANAGE_APPS` permissions.
```suggestion
The App can be installed from [Saleor App Store](developer/app-store/overview.mdx). To install the App, you must have `MANAGE_USERS` and `MANAGE_APPS` [permissions](developer/permissions.mdx#app-permissions).
```

Also, can you add the same section to the Taxes app? 🙏

2023-04-04 07:30 UTC, peelar commented on docs/developer/app-store/apps/crm.mdx
> +The App is configured per provider. You can configure more than one provider - the App will work with at least one provider set up
```suggestion
The App is configured per provider. You can configure multiple providers - the App will work with at least one provider set up.
```

> The App is configured per provider.  

This sentence is a bit unclear to me. When I first read it, I thought it meant that each app could have only one provider, but it is denied in the next sentence.

2023-04-04 07:30 UTC, peelar commented on docs/developer/app-store/apps/crm.mdx
> +### Mailchimp configuration
```suggestion
### Mailchimp
```

2023-04-04 07:30 UTC, peelar commented on docs/developer/app-store/apps/crm.mdx
> +After successful authorization, App will store a token used to connect with a Mailchimp API.
```suggestion
After successful authorization, the App will store a token used to connect with a Mailchimp API.
```

2023-04-04 07:30 UTC, peelar commented on docs/developer/app-store/apps/crm.mdx
> +The App will set a customer in Mailchimp when customer is created (`CUSTOMER_CREATED` event) and updated (`CCUSTOMER_UPDATED` event).
```suggestion
The App will set a customer in Mailchimp when a Saleor customer is created (`CUSTOMER_CREATED` event) or updated (`CUSTOMER_UPDATED` event).
```

2023-04-04 07:30 UTC, peelar commented on docs/developer/app-store/apps/crm.mdx
> +You can do that from the App.
This sentence feels like something is missing here. I suggest providing some more context about where and how the user can do it.

2023-04-04 07:30 UTC, peelar commented on docs/developer/app-store/apps/crm.mdx
> +App will create contacts with "Non-subscribed" status (`transactional` in the API).
```suggestion
The contacts created by the App will have the "Non-subscribed" status (`transactional` in the API).
```

2023-04-04 07:30 UTC, peelar commented on docs/developer/app-store/apps/crm.mdx
> +The App will parse metadata items with the key `mailchimp_tags` and extract tags that will be added to each contact.
```suggestion
The App will parse metadata items with the `mailchimp_tags` key and extract tags that will be added to each contact.
```

2023-04-04 07:30 UTC, peelar commented on docs/developer/app-store/apps/crm.mdx
> +Taxes is a Next.js application. If you want to learn more about setting environment variables in Next.js, head over to the [documentation](https://nextjs.org/docs/basic-features/environment-variables
```suggestion
CRM is a Next.js application. If you want to learn more about setting environment variables in Next.js, head over to the [documentation](https://nextjs.org/docs/basic-features/environment-variables).
```

2023-04-04 07:30 UTC, peelar commented on docs/developer/app-store/apps/index.mdx
> +[**CRM** Synchronize customers with CRM platforms](taxes)
```suggestion
[**CRM** Synchronize customers with CRM platforms](crm)
```

2023-04-04 07:53 UTC, 2can commented
@peelar @lkostrowski deployment issues has been fixed with https://github.com/saleor/saleor-docs/pull/705, please rebase

2023-04-06 12:39 UTC, peelar approved these changes

2023-04-07 07:11 UTC, timuric approved these changes

2023-04-07 07:12 UTC, merged