Split checkout docs
saleor/saleor-docs pull request #777
Opened 2023-05-23 15:53 UTC by timuric

2023-05-23 16:32 UTC, mmiszy requested changes

2023-05-23 16:32 UTC, mmiszy commented on sidebars.js
> +            "developer/checkout/finilizing",
```suggestion
            "developer/checkout/finalizing",
```

2023-05-23 16:32 UTC, mmiszy commented on docs/developer/checkout/finilizing.mdx
typo: `finalizing`

2023-05-24 05:26 UTC, korycins approved these changes

2023-05-24 10:57 UTC, 2can approved these changes

2023-05-24 14:11 UTC, 2can commented
- I will remove the "Checkout" tile from the home screen in the separate PR.
- regarding the "Core concepts" it's a matter of naming, both seems fine to me

2023-05-24 14:12 UTC, zaiste approved these changes

2023-05-24 14:13 UTC, mmiszy approved these changes

2023-05-24 14:13 UTC, merged

2023-08-31 15:03 UTC, patrys commented on sidebars.js
> +        },
You can auto-generate sections based on file structure