Add troubleshooting page for apps development
saleor/saleor-docs pull request #802
Opened 2023-06-15 06:39 UTC by lkostrowski

2023-06-15 06:48 UTC, peelar requested changes

2023-06-15 06:48 UTC, peelar commented on docs/developer/extending/apps/developing-apps/troubleshooting.mdx
> +# I see Typescript errors
```suggestion
# Issues
## I see Typescript errors
```

2023-06-15 06:48 UTC, peelar commented on docs/developer/extending/apps/developing-apps/troubleshooting.mdx
> +Please ensure you have installed right version of pnpm on your machine and re-install dependencies with `pnpm install`.
```suggestion
Please ensure you have installed the right version of pnpm on your machine and re-install dependencies with `pnpm install`.
```

2023-06-15 06:48 UTC, peelar commented on docs/developer/extending/apps/developing-apps/troubleshooting.mdx
> +To find accurate pnpm version in your project, check root `package.json` file and find `packageManager` field.
```suggestion
To find the accurate pnpm version in your project, check the root `package.json` file and look for the `packageManager` field.
```

2023-06-15 06:48 UTC, peelar commented on docs/developer/extending/apps/developing-apps/troubleshooting.mdx
> +For example `"packageManager": "pnpm@8.2.0"` means that you need to install exactly `8.2.0` version of pnpm.
```suggestion
For example: `"packageManager": "pnpm@8.2.0"` means that you need to install exactly the `8.2.0` version of pnpm.
```

2023-06-19 08:21 UTC, peelar approved these changes

2023-06-22 09:28 UTC, patrys commented on docs/developer/extending/apps/developing-apps/troubleshooting.mdx
> +For example: `"packageManager": "pnpm@8.2.0"` means that you need to install exactly the `8.2.0` version of pnpm.
That's good info but also something I'd like to see addressed eventually. Requiring precise micro versions of a globally-installed package requires the use of virtual environments, and I feel we need to document that if we can't have it work with a broader set of package manager releases.

2023-06-22 09:28 UTC, patrys approved these changes

2023-06-22 10:40 UTC, merged