[programmatic-payments] Stored payment methods
saleor/saleor-docs pull request #852
Opened 2023-07-28 10:24 UTC by korycins

2023-07-28 12:10 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/saleor/saleor-docs?pullRequest=852) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/saleor/saleor-docs?pullRequest=852) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: korycins<br/>:x: Maciej Koryciński<br/><hr/>**Maciej Koryciński** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/saleor/saleor-docs?pullRequest=852) it.</sub>

2023-07-31 10:22 UTC, witoszekdev commented on docs/developer/extending/webhooks/synchronous-events/stored-payment-method.mdx
> +Saleor has synchronous webhooks that allow delegating the stored payment method's management to the payment app.
> without providing all payment details

I would add an example:

> without providing all payment details (e.g. 1-click checkout)

2023-07-31 10:22 UTC, witoszekdev commented on docs/developer/payments.mdx
> +Saleor uses synchronous webhooks to notify the payment app about actions (such as list-stored-payment-method) requested by the customer.
I would add a link to `list-stored-payment-method`: https://saleor-docs-1juwt4dfh-saleorcommerce.vercel.app/docs/3.x/developer/extending/webhooks/synchronous-events/stored-payment-method#list-stored-payment-methods

2023-07-31 13:00 UTC, patrys commented
Can we regenerate docs on `main` and then redo this PR? It rewrites the entire API reference 😢

2023-08-02 10:46 UTC, 2can commented
@patrys @korycins docs regenerated here https://github.com/saleor/saleor-docs/pull/858

2023-08-02 13:03 UTC, 2can commented
@korycins https://github.com/saleor/saleor-docs/pull/858 merged, please rebase or re-generate

2023-08-04 13:23 UTC, korycins commented
@2can  @patrys  branch rebased. I've re-generated the api-reference based on the schema from my feature branch. Still, there are a lot of modified fields. We should agree to always generate the schema from main saleor branch or figure out a different approach.

2023-08-07 12:34 UTC, patrys commented
I don't know how to review this 😢

2023-08-18 13:02 UTC, mmiszy requested changes

2023-08-18 13:02 UTC, mmiszy commented on docs/developer/extending/webhooks/synchronous-events/stored-payment-method.mdx
> +      "data": "<[Optional] JSON data tha will be returned to storefront>"
```suggestion
      "supportedPaymentFlows": "<list of supported flows that can be performed with this payment method>",
      "type": "<type of the payment method. For example: Credit Card>",
      // "creditCardInfo": [Optional] credit card information if the payment method is a credit card.
      "creditCardInfo": {
        "brand": "<credit card brand>",
        "lastDigits": "<last digits>",
        "expMonth": "<expiration month>",
        "expYear": "<expiration year>",
        "firstDigits": "<[Optional] first digits>"
      },
      "name": "<[Optional] name of the payment method. For example: last 4 digits of credit card, obfuscated email>",
      "data": "<[Optional] JSON data that will be returned to storefront>"
```

2023-08-25 11:19 UTC, mmiszy approved these changes

2023-08-25 11:26 UTC, 2can approved these changes

2023-08-25 11:45 UTC, peelar approved these changes

2023-08-25 12:37 UTC, merged