Add docs for new Segment app
saleor/saleor-docs pull request #873
Opened 2023-08-10 16:36 UTC by lkostrowski

2023-08-11 06:04 UTC, peelar requested changes

2023-08-11 06:04 UTC, peelar commented on docs/developer/app-store/apps/segment.mdx
> +## Pre-requisites
**suggestion (blocking)**:

```suggestion
## Prerequisites
```

2023-08-11 06:04 UTC, peelar commented on docs/developer/app-store/apps/segment.mdx
> +3. Name the source you want, e.g., "Saleor Orders."
**suggestion (non-blocking)**:

```suggestion
3. Name the source, e.g., "Saleor Orders."
```

2023-08-11 06:04 UTC, peelar commented on docs/developer/app-store/apps/segment.mdx
> +2. Create a new connection source and set it to `Node.js`.
**suggestion (non-blocking)**:

If we can, I suggest linking to some Segment docs here.

2023-08-11 06:04 UTC, peelar commented on docs/developer/app-store/apps/segment.mdx
> +The app requires configuring only a single field - a Segment Write Key.
**suggestion (non-blocking)**:

```suggestion
The app requires configuring only one field - a [Segment Write Key](https://segment.com/docs/connections/find-writekey/).
```

2023-08-11 06:04 UTC, peelar commented on docs/developer/app-store/apps/segment.mdx
> +The easiest way to test if the app is configured is to perform following steps:
**suggestion (non-blocking)**:

```suggestion
The easiest way to test if the app is configured correctly is to perform the following steps:
```

2023-08-16 09:12 UTC, lkostrowski commented
@peelar applied fixes

2023-08-16 10:38 UTC, 2can approved these changes

2023-08-21 08:29 UTC, peelar approved these changes

2023-08-22 13:32 UTC, merged