Programmatic payments stored payment methods request delete
saleor/saleor-docs pull request #878
Opened 2023-08-14 13:06 UTC by korycins

2023-08-18 12:51 UTC, mmiszy requested changes

2023-08-18 12:51 UTC, mmiszy commented on docs/developer/extending/webhooks/synchronous-events/stored-payment-method.mdx
> +  "message": "<Optionall, message that will be passed to the frontend>"
```suggestion
  "success": "<Boolean, determines the status of the requested action.>",
  "message": "<Optional, message that will be passed to the frontend>"
```

2023-08-18 12:51 UTC, mmiszy commented on docs/developer/extending/webhooks/synchronous-events/stored-payment-method.mdx
> +  "success": "<Boolean, determine the status of the requested action.>",
Now I'm wondering if it wouldn't make more sense to pass `status` (enum) instead of a boolean. Similar to `TransactionEventTypeEnum`

2023-08-18 12:51 UTC, mmiszy commented on docs/developer/payments.mdx
> +or [User.storedPaymentMethod](api-storefront/users/objects/user.mdx#code-style-fontweight-normal-userbstoredpaymentmethodsbcodestoredpaymentmethod--)
Shouldn't this also be plural?
```suggestion
or [User.storedPaymentMethods](api-storefront/users/objects/user.mdx#code-style-fontweight-normal-userbstoredpaymentmethodsbcodestoredpaymentmethod--)
```

2023-09-07 10:08 UTC, peelar approved these changes

2023-09-07 10:08 UTC, peelar commented on docs/developer/extending/webhooks/synchronous-events/stored-payment-method.mdx
> +More details about flow can be found [here](developer/payments.mdx#requesting-deletion-of-stored-payment-method).
**polish**:

```suggestion
A synchronous webhook [STORED_PAYMENT_METHOD_DELETE_REQUESTED](api-reference/webhooks/enums/webhook-event-type-sync-enum.mdx#code-style-fontweight-normal-webhookeventtypesyncenumbstored_payment_method_delete_requestedbcode) is called when the user requests the deletion of the stored payment method. User can request the deletion of the stored payment method by triggering the mutation [storedPaymentMethodRequestDelete](api-reference/payments/mutations/stored-payment-method-request-delete.mdx).
More details about the flow can be found [here](developer/payments.mdx#requesting-deletion-of-stored-payment-method).
```

2023-09-07 10:27 UTC, korycins commented on docs/developer/extending/webhooks/synchronous-events/stored-payment-method.mdx
> +  "user_id": "VXNlcjoyOA==",
Of course. Thanks for catching this. I forgot to add it in the docs.

2023-09-07 11:12 UTC, mmiszy approved these changes

2023-09-07 11:35 UTC, 2can approved these changes

2023-09-07 11:35 UTC, 2can commented on docs/developer/payments.mdx
> +The user can request a deletion of their stored payment methods. Saleor doesn't store directly a user's payment methods or transmits payment method details.
```suggestion
The user can request a deletion of their stored payment methods. Saleor doesn't store directly a user's payment methods or transmit payment method details.
```

2023-09-07 11:39 UTC, merged