changed "Go here for more information" to "Learn more."
saleor/saleor-docs pull request #938
Opened 2023-09-06 18:28 UTC by narayandabu

fixes #936

![image](https://github.com/saleor/saleor-docs/assets/48639860/0ec147a7-0296-408c-97d4-3f2158a6a239)

2023-09-06 18:28 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/saleor/saleor-docs?pullRequest=938) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/saleor/saleor-docs?pullRequest=938) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/saleor/saleor-docs?pullRequest=938) it.</sub>

2023-09-06 18:31 UTC, patrys commented on docs/developer/stock-allocation.mdx
> +- channel - allows configuring your shop differently for different currencies. [Learn More](./channels.mdx).
```suggestion
- channel - allows configuring your shop differently for different currencies. See the [channel documentation](./channels.mdx) for details.
```

2023-09-07 19:42 UTC, narayandabu commented
sorry for a late response to this but i have made the changes should directly put a pull request for the changes made  in the version3.x

2023-09-08 13:08 UTC, 2can requested changes

2023-09-08 13:08 UTC, 2can commented on versioned_docs/version-3.x/developer/stock-allocation.mdx
> +- channel - allows configuring your shop differently for different currencies.See the [channel documentation](./channels.mdx) for details.
```suggestion
- channel - allows configuring your shop differently for different currencies. See the [channel documentation](./channels.mdx) for details.
```

2023-09-12 18:27 UTC, 2can approved these changes

2023-09-12 18:27 UTC, merged