New zero-downtime case examples
saleor/saleor-docs pull request #939
Opened 2023-09-06 19:29 UTC by kadewu

Add missing `removing index` case and as well cover foreign key case.

2023-09-07 07:57 UTC, michal-macioszczyk approved these changes

2023-09-08 08:45 UTC, IKarbowiak approved these changes

2023-09-12 16:58 UTC, 2can requested changes

2023-09-12 16:58 UTC, 2can commented on docs/developer/community/zero-downtime-migrations.mdx
> +Similarly to adding the index to the database, removing the index also needs `concurrently` option.
```suggestion
Similarly to adding the index to the database, removing the index also needs the `concurrently` option.
```

2023-09-12 16:58 UTC, 2can commented on versioned_docs/version-3.x/developer/community/zero-downtime-migrations.mdx
> +Similarly to adding the index to the database, removing the index also needs `concurrently` option.
```suggestion
Similarly to adding the index to the database, removing the index also needs the `concurrently` option.
```

2023-09-13 08:51 UTC, kadewu commented
Alongside applying review suggestions, also added small note about nonatomic migrations that is needed in the concurrently build.

2023-09-15 11:34 UTC, 2can requested changes

2023-09-15 11:34 UTC, 2can commented on docs/developer/community/zero-downtime-migrations.mdx
> +Migration containing the `ForeighKey` creation should be separated from migration that creates an index concurrently.
```suggestion
Migration containing the `ForeignKey` creation should be separated from migration that creates an index concurrently.
```

2023-09-15 11:34 UTC, 2can commented on versioned_docs/version-3.x/developer/community/zero-downtime-migrations.mdx
> +Migration containing the `ForeighKey` creation should be separated from migration that creates an index concurrently.
```suggestion
Migration containing the `ForeignKey` creation should be separated from migration that creates an index concurrently.
```

2023-09-18 07:40 UTC, 2can approved these changes

2023-09-18 07:40 UTC, merged